CC := g++-7
STD := -std=c++14
CFLAGS := -Wall -pthread

all: example1 example2 example3 example4

example1: example.cpp
	$(CC) $(STD) $(CFLAGS) example.cpp -o example1

example2: example2.cpp
	$(CC) $(STD) $(CFLAGS) example2.cpp -o example2

example3: example3.cpp
	$(CC) $(STD) $(CFLAGS) example3.cpp -o example3

example4: example4.cpp
	$(CC) $(STD) $(CFLAGS) example4.cpp -o example4
